# Generated by Django 5.0.1 on 2024-02-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='tariff',
        ),
        migrations.AddField(
            model_name='parkingreservation',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
